-- dynisle blur/opacity settings - AUTHORITATIVE, loaded last on purpose.
--
-- Why this file exists: `hyprland/shellOverrides/main.lua` is regenerated by
-- illogical-impulse (`qs -c ii`) from ~/.config/illogical-impulse/config.json.
-- Every accidental ii launch rewrites the keys ii manages and silently resets
-- blur.size to 1 (invisible blur) plus active_opacity to 1 (no translucency for
-- blur to act on). That is what made blur appear to "work and then stop".
--
-- hyprland.lua loads this AFTER shellOverrides.main, so these win even right
-- after ii has clobbered that file. Note `custom/rules.lua` and
-- `custom/general.lua` load BEFORE shellOverrides and therefore cannot win -
-- that is why this is a separate require at the very end.
--
-- Residual risk: if ii ever regenerates hyprland.lua itself, the require line
-- disappears and blur breaks again. Check that first if blur mysteriously dies.

-- A real blur radius. ii forces this to 1, which is effectively no blur.
hl.config({ decoration = { blur = { enabled = true } } })
hl.config({ decoration = { blur = { size = 8 } } })
hl.config({ decoration = { blur = { passes = 3 } } })

-- Blur only affects what sits behind translucent pixels, so windows need some
-- alpha for it to have anything to work on. At 0.92 only 8% of the backdrop
-- showed through and the effect was imperceptible; 0.85 was measured and chosen.
hl.config({ decoration = { active_opacity = 0.75 } })
hl.config({ decoration = { inactive_opacity = 0.65 } })

-- Games and video are never made translucent, whatever the values above are.
hl.config({ decoration = { fullscreen_opacity = 1.0 } })

-- ON, and this was WRONG before. It was set to `false` to dodge a stale blur
-- cache, and the cost was never noticed: with new_optimizations off, Hyprland
-- 0.56.2 does not blur LAYER SURFACES AT ALL. dynisle is a layer surface, so
-- the island and its full-screen veil dimmed the screen and blurred nothing -
-- MEASURED, edge energy 9.19 veiled versus 9.29 clear, and text behind the
-- veil stayed readable at 85% black. With it on: 6.85 and an unreadable wash.
--
-- The stale-cache worry is handled by turning xray off per-layer below, which
-- is the actual cause of the bug that motivated this line.
hl.config({ decoration = { blur = { new_optimizations = true } } })

-- xray OFF. This is what made the island's blur keep showing the OLD wallpaper
-- after a new one was applied: with xray on, Hyprland blurs a SNAPSHOT of the
-- desktop background instead of whatever is actually behind the surface, and
-- that snapshot is not retaken when the wallpaper changes. hyprland/general.lua
-- turns it on; this file loads last, so this wins.
-- Off also means the island blurs the real windows underneath it, which is what
-- "blur" was supposed to mean here all along (vault/notes.md fact 1).
hl.config({ decoration = { blur = { xray = false } } })


-- xray OFF FOR THIS LAYER SPECIFICALLY. `hyprland/rules.lua` turns it on for
-- EVERY namespace (`.*`), and with the blur cache back on that rule bites: the
-- veil blurred a snapshot of the wallpaper instead of the windows actually
-- behind it, which is the same bug as notes.md fact 1 wearing a different hat.
-- The global `decoration:blur:xray = false` above does not cover a per-layer
-- rule; this does.
hl.layer_rule({ match = { namespace = "quickshell:dynisle" }, xray = false })
